export const SERVER_ERROR_TYPES = {
  // common 에러
  UNKNOWN: 'UNKNOWN',
  INTERNAL: 'INTERNAL',

  // 요청 함수 에러
  CHARACTER_FULL_INFO_FETCH_ERROR: 'CHARACTER_FULL_INFO_FETCH_ERROR',
  CHARACTERS_FETCH_ERROR: 'CHARACTERS_FETCH_ERROR',
  CHARACTER_FETCH_ERROR: 'CHARACTER_FETCH_ERROR',
  NOTICES_FETCH_ERROR: 'NOTICES_FETCH_ERROR',
  NOTICE_FETCH_ERROR: 'NOTICE_FETCH_ERROR',

  // 로직 에러
  POWER_FILTER_MIN_LEVEL: 'POWER_FILTER_MIN_LEVEL',
  STAT_PARSE_ERROR: 'STAT_PARSE_ERROR',
  NOTICE_TYPE_ERROR: 'STAT_PARSE_ERROR',

  // 넥슨 api 에러 타입
  NEXON_API: 'NEXON_API',
  NEXON_SERVER: 'NEXON_SERVER',
  NEXON_PER_MISSION: 'NEXON_PER_MISSION',
  NEXON_INVALID_IDENTIFIER: 'NEXON_INVALID_IDENTIFIER',
  NEXON_INVALID_PARAMETER: 'NEXON_INVALID_PARAMETER',
  NEXON_INVALID_API_KEY: 'NEXON_INVALID_API_KEY',
  NEXON_INVALID_PATH: 'NEXON_INVALID_PATH',
  NEXON_RATE_LIMIT: 'NEXON_RATE_LIMIT',
  NEXON_DATA_PREPARING: 'NEXON_DATA_PREPARING',
  NEXON_GAME_MAINTENANCE: 'NEXON_GAME_MAINTENANCE',
  NEXON_API_MAINTENANCE: 'NEXON_API_MAINTENANCE',
} as const
