export const STAT_KEY = {
  'AP 배분 DEX': 'ap_dex',
  'AP 배분 HP': 'ap_hp',
  'AP 배분 INT': 'ap_int',
  'AP 배분 LUK': 'ap_luk',
  'AP 배분 MP': 'ap_mp',
  'AP 배분 STR': 'ap_str',
  DEX: 'dex',
  HP: 'hp',
  INT: 'int',
  LUK: 'luk',
  MP: 'mp',
  STR: 'str',
  '공격 속도': 'attack_speed',
  공격력: 'attack_power',
  데미지: 'damage',
  마력: 'magic_attack',
  '메소 획득량': 'meso_gain',
  '무기 숙련도': 'weapon_mastery',
  방어력: 'defense',
  '방어율 무시': 'ignore_defense',
  '버프 지속시간': 'buff_duration',
  '보스 몬스터 데미지': 'boss_damage',
  '상태이상 내성': 'status_resistance',
  '상태이상 추가 데미지': 'abnormal_damage',
  '소환수 지속시간 증가': 'summon_duration',
  '속성 내성 무시': 'ignore_elemental_resistance',
  스타포스: 'star_force',
  스탠스: 'stance',
  '아이템 드롭률': 'item_drop_rate',
  아케인포스: 'arcane_force',
  어센틱포스: 'authentic_force',
  이동속도: 'speed',
  '일반 몬스터 데미지': 'normal_monster_damage',
  '재사용 대기시간 감소 (%)': 'cooldown_reduction_percent',
  '재사용 대기시간 감소 (초)': 'cooldown_reduction_second',
  '재사용 대기시간 미적용': 'cooldown_ignore',
  전투력: 'combat_power',
  점프력: 'jump',
  '최대 스탯공격력': 'max_stat_attack',
  '최소 스탯공격력': 'min_stat_attack',
  '최종 데미지': 'final_damage',
  '추가 경험치 획득': 'bonus_exp',
  '크리티컬 데미지': 'critical_damage',
  '크리티컬 확률': 'critical_rate',
} as const
