import { ClearedBoss } from '@/types/storage/JubocCharacter'

export type PresetBoss = {
  id: string
  name: string
  tip: string
  minPower: number
  bossEntries: ClearedBoss[]
}

export const PRESET_BOSSES: PresetBoss[] = [
  {
    id: 'sde',
    name: '스데',
    tip: '전투력 500 이상',
    minPower: 5000000,
    bossEntries: [
      { bossId: 'Zakum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Magnus', difficulty: '하드', partySize: 1 },
      { bossId: 'Hilla', difficulty: '하드', partySize: 1 },
      { bossId: 'Papulatus', difficulty: '카오스', partySize: 1 },
      { bossId: 'Pierre', difficulty: '카오스', partySize: 1 },
      { bossId: 'BanBan', difficulty: '카오스', partySize: 1 },
      { bossId: 'BloodyQueen', difficulty: '카오스', partySize: 1 },
      { bossId: 'Vellum', difficulty: '카오스', partySize: 1 },
      { bossId: 'PinkBean', difficulty: '카오스', partySize: 1 },
      { bossId: 'Cygnus', difficulty: '노멀', partySize: 1 },
      { bossId: 'Lotus', difficulty: '노멀', partySize: 1 },
      { bossId: 'Damien', difficulty: '노멀', partySize: 1 },
    ],
  },
  {
    id: 'gaenseul',
    name: '가엔슬',
    tip: '전투럭 1천 이상',
    minPower: 10000000,
    bossEntries: [
      { bossId: 'Zakum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Magnus', difficulty: '하드', partySize: 1 },
      { bossId: 'Papulatus', difficulty: '카오스', partySize: 1 },
      { bossId: 'Pierre', difficulty: '카오스', partySize: 1 },
      { bossId: 'BanBan', difficulty: '카오스', partySize: 1 },
      { bossId: 'BloodyQueen', difficulty: '카오스', partySize: 1 },
      { bossId: 'Vellum', difficulty: '카오스', partySize: 1 },
      { bossId: 'PinkBean', difficulty: '카오스', partySize: 1 },
      { bossId: 'Cygnus', difficulty: '노멀', partySize: 1 },
      { bossId: 'Lotus', difficulty: '노멀', partySize: 1 },
      { bossId: 'Damien', difficulty: '노멀', partySize: 1 },
      { bossId: 'GuardianAngelSlime', difficulty: '카오스', partySize: 1 },
    ],
  },
  {
    id: 'irushi',
    name: '이루시',
    tip: '전투럭 1천 500 이상',
    minPower: 15000000,
    bossEntries: [
      { bossId: 'Zakum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Magnus', difficulty: '하드', partySize: 1 },
      { bossId: 'Papulatus', difficulty: '카오스', partySize: 1 },
      { bossId: 'Pierre', difficulty: '카오스', partySize: 1 },
      { bossId: 'BanBan', difficulty: '카오스', partySize: 1 },
      { bossId: 'BloodyQueen', difficulty: '카오스', partySize: 1 },
      { bossId: 'Vellum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Cygnus', difficulty: '노멀', partySize: 1 },
      { bossId: 'Lotus', difficulty: '노멀', partySize: 1 },
      { bossId: 'Damien', difficulty: '노멀', partySize: 1 },
      { bossId: 'GuardianAngelSlime', difficulty: '노멀', partySize: 1 },
      { bossId: 'Lucid', difficulty: '이지', partySize: 1 },
    ],
  },
  {
    id: 'ruwill',
    name: '이루윌',
    tip: '전투럭 2천 이상',
    minPower: 20000000,
    bossEntries: [
      { bossId: 'Zakum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Magnus', difficulty: '하드', partySize: 1 },
      { bossId: 'Papulatus', difficulty: '카오스', partySize: 1 },
      { bossId: 'Pierre', difficulty: '카오스', partySize: 1 },
      { bossId: 'BanBan', difficulty: '카오스', partySize: 1 },
      { bossId: 'BloodyQueen', difficulty: '카오스', partySize: 1 },
      { bossId: 'Vellum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Lotus', difficulty: '노멀', partySize: 1 },
      { bossId: 'Damien', difficulty: '노멀', partySize: 1 },
      { bossId: 'GuardianAngelSlime', difficulty: '노멀', partySize: 1 },
      { bossId: 'Lucid', difficulty: '이지', partySize: 1 },
      { bossId: 'Will', difficulty: '이지', partySize: 1 },
    ],
  },
  {
    id: 'hasuu',
    name: '하스우',
    tip: '전투럭 3천 이상',
    minPower: 30000000,
    bossEntries: [
      { bossId: 'Magnus', difficulty: '하드', partySize: 1 },
      { bossId: 'Papulatus', difficulty: '카오스', partySize: 1 },
      { bossId: 'Pierre', difficulty: '카오스', partySize: 1 },
      { bossId: 'BloodyQueen', difficulty: '카오스', partySize: 1 },
      { bossId: 'Vellum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Lotus', difficulty: '하드', partySize: 1 },
      { bossId: 'Damien', difficulty: '하드', partySize: 1 },
      { bossId: 'GuardianAngelSlime', difficulty: '노멀', partySize: 1 },
      { bossId: 'Lucid', difficulty: '노멀', partySize: 1 },
      { bossId: 'Will', difficulty: '노멀', partySize: 1 },
      { bossId: 'GiantMonsterGloom', difficulty: '노멀', partySize: 1 },
      { bossId: 'GuardCaptainDarknell', difficulty: '노멀', partySize: 1 },
    ],
  },
  {
    id: 'geommitsol',
    name: '검밑솔',
    tip: '전투럭 1억 이상',
    minPower: 100000000,
    bossEntries: [
      { bossId: 'Magnus', difficulty: '하드', partySize: 1 },
      { bossId: 'Papulatus', difficulty: '카오스', partySize: 1 },
      { bossId: 'BloodyQueen', difficulty: '카오스', partySize: 1 },
      { bossId: 'Vellum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Lotus', difficulty: '하드', partySize: 1 },
      { bossId: 'Damien', difficulty: '하드', partySize: 1 },
      { bossId: 'GuardianAngelSlime', difficulty: '카오스', partySize: 1 },
      { bossId: 'Lucid', difficulty: '하드', partySize: 1 },
      { bossId: 'Will', difficulty: '하드', partySize: 1 },
      { bossId: 'GiantMonsterGloom', difficulty: '카오스', partySize: 1 },
      { bossId: 'VerusHilla', difficulty: '하드', partySize: 1 },
      { bossId: 'GuardCaptainDarknell', difficulty: '하드', partySize: 1 },
    ],
  },
  {
    id: 'haseikal',
    name: '하세이칼',
    tip: '전투럭 1억 5천 이상',
    minPower: 150000000,
    bossEntries: [
      { bossId: 'Papulatus', difficulty: '카오스', partySize: 1 },
      { bossId: 'Vellum', difficulty: '카오스', partySize: 1 },
      { bossId: 'Lotus', difficulty: '하드', partySize: 1 },
      { bossId: 'Damien', difficulty: '하드', partySize: 1 },
      { bossId: 'GuardianAngelSlime', difficulty: '카오스', partySize: 1 },
      { bossId: 'Lucid', difficulty: '하드', partySize: 1 },
      { bossId: 'Will', difficulty: '하드', partySize: 1 },
      { bossId: 'GiantMonsterGloom', difficulty: '카오스', partySize: 1 },
      { bossId: 'VerusHilla', difficulty: '하드', partySize: 1 },
      { bossId: 'GuardCaptainDarknell', difficulty: '하드', partySize: 1 },
      { bossId: 'ChosenSeren', difficulty: '하드', partySize: 1 },
      { bossId: 'KalostheGuardian', difficulty: '이지', partySize: 1 },
    ],
  },
  {
    id: 'nokallica',
    name: '노칼이카',
    tip: '전투럭 2억 이상',
    minPower: 200000000,
    bossEntries: [
      { bossId: 'Lotus', difficulty: '하드', partySize: 1 },
      { bossId: 'Damien', difficulty: '하드', partySize: 1 },
      { bossId: 'GuardianAngelSlime', difficulty: '카오스', partySize: 1 },
      { bossId: 'Lucid', difficulty: '하드', partySize: 1 },
      { bossId: 'Will', difficulty: '하드', partySize: 1 },
      { bossId: 'GiantMonsterGloom', difficulty: '카오스', partySize: 1 },
      { bossId: 'VerusHilla', difficulty: '하드', partySize: 1 },
      { bossId: 'GuardCaptainDarknell', difficulty: '하드', partySize: 1 },
      { bossId: 'ChosenSeren', difficulty: '하드', partySize: 1 },
      { bossId: 'KalostheGuardian', difficulty: '노멀', partySize: 1 },
      { bossId: 'TheFirstAdversary', difficulty: '노멀', partySize: 1 },
      { bossId: 'Kaling', difficulty: '이지', partySize: 1 },
    ],
  },
] satisfies readonly PresetBoss[]
